[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 10
